//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeteccionTexturas.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class textura
    {
        public int id { get; set; }
        public Nullable<int> R { get; set; }
        public Nullable<int> G { get; set; }
        public Nullable<int> B { get; set; }
        public int id_ima { get; set; }
        public Nullable<int> pR { get; set; }
        public Nullable<int> pG { get; set; }
        public Nullable<int> pB { get; set; }
    
        public virtual imagenes imagenes { get; set; }
    }
}
